language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=website.settings_travis

script:
  - python manage.py migrate
  - python manage.py test