# Generated by Django 3.1.5 on 2021-02-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0003_product_nutriment_fiber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
