# Generated by Django 3.1.5 on 2021-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0004_auto_20210214_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
