# Generated by Django 3.1.6 on 2021-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0005_auto_20210214_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eco_score',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
