# Generated by Django 3.1.5 on 2021-02-01 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(max_length=13, unique=True)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('nutri_score', models.CharField(max_length=1)),
                ('image', models.CharField(max_length=1024, null=True)),
                ('nutriment_energy', models.FloatField(null=True)),
                ('nutriment_sugars', models.FloatField(null=True)),
                ('nutriment_salt', models.FloatField(null=True)),
                ('nutriment_fat', models.FloatField(null=True)),
                ('nutriment_saturated_fat', models.FloatField(null=True)),
                ('nutriment_sodium', models.FloatField(null=True)),
                ('nutriment_proteins', models.FloatField(null=True)),
                ('nutriment_carbohydrates', models.FloatField(null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purbeurre.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_substitute_products', to='purbeurre.product')),
                ('substitute_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_substitute_substitute_product', to='purbeurre.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_substitute_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'substitute_product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_store_products', to='purbeurre.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_store_stores', to='purbeurre.store')),
            ],
            options={
                'unique_together': {('product', 'store')},
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_brands', to='purbeurre.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand_products', to='purbeurre.product')),
            ],
            options={
                'unique_together': {('product', 'brand')},
            },
        ),
    ]
