# Generated by Django 3.1.5 on 2021-02-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productbrand',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productstore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productstore',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstore',
            name='store',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
        migrations.DeleteModel(
            name='ProductStore',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
